"""add unique constraint on bars instrument+interval+bar_start

Revision ID: 13b805fca4ca
Revises: 2af91de317bb
Create Date: 2026-08-16 22:26:59.292036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b805fca4ca'
down_revision = '2af91de317bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_bars_instrument_interval_start', 'bars', ['instrument_id', 'interval', 'bar_start'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_bars_instrument_interval_start', 'bars', type_='unique')
    # ### end Alembic commands ###
