"""add fee_policies, fx_rates, fills.realized_pnl

Revision ID: 1c0aa76bf61d
Revises: 852b71c33eea
Create Date: 2026-08-16 11:52:16.855457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0aa76bf61d'
down_revision = '852b71c33eea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_policies',
    sa.Column('market', sa.String(length=8), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('commission_bps', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('sell_tax_bps', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('min_commission', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('spread_bps', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'version', name='uq_fee_policies_market_version')
    )
    op.create_table('fx_rates',
    sa.Column('base_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('quote_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('spread_bps', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fills', sa.Column('realized_pnl', sa.Numeric(precision=24, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fills', 'realized_pnl')
    op.drop_table('fx_rates')
    op.drop_table('fee_policies')
    # ### end Alembic commands ###
