"""initial schema: users, market, portfolio, journal

Revision ID: 852b71c33eea
Revises: 
Create Date: 2026-08-16 09:03:29.439308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '852b71c33eea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('is_tradable', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('thesis', sa.Text(), nullable=True),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('counter_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_holding_period', sa.String(length=64), nullable=True),
    sa.Column('entry_condition', sa.Text(), nullable=True),
    sa.Column('target_condition', sa.Text(), nullable=True),
    sa.Column('stop_loss_condition', sa.Text(), nullable=True),
    sa.Column('planned_amount', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('planned_weight_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('confidence_level', sa.Integer(), nullable=True),
    sa.Column('reference_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_data_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actual_entry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_exit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('followed_plan', sa.Boolean(), nullable=True),
    sa.Column('plan_change_reason', sa.Text(), nullable=True),
    sa.Column('expectation_gap', sa.Text(), nullable=True),
    sa.Column('luck_contribution', sa.Text(), nullable=True),
    sa.Column('behavior_to_repeat', sa.Text(), nullable=True),
    sa.Column('behavior_to_change', sa.Text(), nullable=True),
    sa.Column('emotion_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('process_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('process_score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('auth_provider', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bars',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('bar_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consents',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=32), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('agreed', sa.Boolean(), nullable=False),
    sa.Column('agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('push_token', sa.String(length=256), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_versions',
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('author_type', sa.String(length=16), nullable=False),
    sa.Column('content_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted_by_user', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ledger_entries',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('account_code', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'event_id', 'account_code', name='uq_ledger_event_once')
    )
    op.create_table('orders',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('pre_trade_journal_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("order_type IN ('MARKET','LIMIT')", name='ck_orders_order_type'),
    sa.CheckConstraint("side IN ('BUY','SELL')", name='ck_orders_side'),
    sa.CheckConstraint('quantity > 0', name='ck_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'idempotency_key', name='uq_orders_idempotency')
    )
    op.create_table('positions',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'instrument_id', name='uq_positions_portfolio_instrument')
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('experience_level', sa.String(length=16), nullable=True),
    sa.Column('interested_markets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interested_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('daily_study_minutes', sa.Integer(), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('locale', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('fills',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('tax', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('market_data_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('refresh_token_hash', sa.String(length=256), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_session_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('fills')
    op.drop_table('profiles')
    op.drop_table('positions')
    op.drop_table('orders')
    op.drop_table('ledger_entries')
    op.drop_table('journal_versions')
    op.drop_table('devices')
    op.drop_table('consents')
    op.drop_table('bars')
    op.drop_table('users')
    op.drop_table('portfolios')
    op.drop_table('journal_entries')
    op.drop_table('instruments')
    # ### end Alembic commands ###
