"""add seven-day challenge and badge tables

Revision ID: 937dbb491085
Revises: d5d5285c1108
Create Date: 2026-08-22 06:50:01.165069

새 테이블만 추가한다 — 기존 사용자 데이터에는 영향이 없다(app/domain/challenge.py
모듈 docstring 참고). 콘텐츠·챌린지·배지 정의 자체의 seed는 별도 migration
(seed_seven_day_challenge_and_badges)에서 멱등하게 반영한다.

동시성 방어선: user_challenges(user_id, challenge_id),
user_mission_progress(user_challenge_id, challenge_mission_id),
user_badges(user_id, badge_definition_id) unique 제약이 각각 "중복 시작 금지",
"동일 미션 중복 완료·중복 XP 지급 금지", "동일 배지 중복 발급 금지"의 최종
방어선이다.
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '937dbb491085'
down_revision = 'd5d5285c1108'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_definitions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition_type', sa.String(length=48), nullable=False),
    sa.Column('condition_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('challenges',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('challenge_days',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'day_number', name='uq_challenge_days_challenge_day')
    )
    op.create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_definition_id', sa.UUID(), nullable=False),
    sa.Column('badge_version', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('awarded_by', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['badge_definition_id'], ['badge_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'badge_definition_id', name='uq_user_badges_user_badge')
    )
    op.create_table('user_challenges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('challenge_version', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_date_local', sa.Date(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_user_challenges_user_challenge')
    )
    op.create_table('challenge_missions',
    sa.Column('challenge_day_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('mission_type', sa.String(length=48), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_day_id'], ['challenge_days.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_day_id', 'code', name='uq_challenge_missions_day_code')
    )
    op.create_table('user_challenge_days',
    sa.Column('user_challenge_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('first_available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_challenge_id'], ['user_challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_challenge_id', 'day_number', name='uq_user_challenge_days_uc_day')
    )
    op.create_table('user_mission_progress',
    sa.Column('user_challenge_id', sa.UUID(), nullable=False),
    sa.Column('challenge_mission_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('evidence_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('xp_awarded', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_mission_id'], ['challenge_missions.id'], ),
    sa.ForeignKeyConstraint(['user_challenge_id'], ['user_challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_challenge_id', 'challenge_mission_id', name='uq_ump_user_challenge_mission')
    )
    # 'uq_instruments_active_exchange_ticker' 관련 diff는 autogenerate의
    # 오탐이다 — 그 partial unique index는 이전 데이터 migration(94b30d15c128)이
    # raw SQL로 만들었을 뿐 어떤 모델의 __table_args__에도 선언돼 있지 않아,
    # 모델 메타데이터와 비교하는 autogenerate가 "삭제된 것"으로 오인한다.
    # 실제로는 그대로 있어야 하므로 drop/recreate 구문을 넣지 않는다.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_mission_progress')
    op.drop_table('user_challenge_days')
    op.drop_table('challenge_missions')
    op.drop_table('user_challenges')
    op.drop_table('user_badges')
    op.drop_table('challenge_days')
    op.drop_table('challenges')
    op.drop_table('badge_definitions')
    # ### end Alembic commands ###
