"""add bias_events table for rule-versioned bias detection

Revision ID: b5ae854dc4ef
Revises: cb3cb7383a73
Create Date: 2026-08-22 08:58:55.146843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5ae854dc4ef'
down_revision = 'cb3cb7383a73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bias_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bias_code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('rule_version', sa.String(length=16), nullable=False),
    sa.Column('threshold_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('minimum_sample_size', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('evidence_strength', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=False),
    sa.Column('self_check_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_lesson_id', sa.UUID(), nullable=True),
    sa.Column('evidence_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'bias_code', 'rule_version', 'evidence_fingerprint', name='uq_bias_events_user_code_version_fingerprint')
    )
    op.create_index('ix_bias_events_user_id', 'bias_events', ['user_id'])
    # 주의: autogenerate가 instruments.uq_instruments_active_exchange_ticker를
    # "삭제된 인덱스"로 잘못 감지해 drop/recreate를 제안했다 — 이 인덱스는
    # 원래 raw SQL로 만들어져 어떤 SQLAlchemy 모델에도 선언돼 있지 않아
    # autogenerate가 매번 이렇게 오탐한다(이전 마이그레이션들에서도 동일하게
    # 수동으로 제거함). 여기서는 아무것도 건드리지 않는다.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bias_events')
    # ### end Alembic commands ###
