"""도메인 전반에서 쓰는 상수. 매직 스트링을 한 곳에 모은다."""

ACCOUNT_CASH = "CASH"

ENTRY_INITIAL_DEPOSIT = "INITIAL_DEPOSIT"
ENTRY_BUY_TRADE = "BUY_TRADE"
ENTRY_SELL_TRADE = "SELL_TRADE"

# 주문 상태 머신 (6.6)
ORDER_CREATED = "CREATED"
ORDER_VALIDATED = "VALIDATED"
ORDER_ACCEPTED = "ACCEPTED"
ORDER_PARTIALLY_FILLED = "PARTIALLY_FILLED"
ORDER_FILLED = "FILLED"
ORDER_CANCELLED = "CANCELLED"
ORDER_EXPIRED = "EXPIRED"
ORDER_VALIDATION_FAILED = "VALIDATION_FAILED"
ORDER_REJECTED = "REJECTED"

ORDER_TERMINAL_STATUSES = {
    ORDER_FILLED,
    ORDER_CANCELLED,
    ORDER_EXPIRED,
    ORDER_VALIDATION_FAILED,
    ORDER_REJECTED,
}

EXCHANGE_MARKET_MAP = {
    "KRX": "KR",
    "KOSPI": "KR",
    "KOSDAQ": "KR",
    "NASDAQ": "US",
    "NYSE": "US",
    "AMEX": "US",
}

FEE_POLICY_VERSION = "v1"

# 시세 신선도 상태 (Phase A: MarketDataService.get_price_point가 판단).
# FRESH: 임계값 이내의 최신 bar. STALE: bar는 있지만 임계값을 넘겨 오래됨 —
# 주문은 차단하되 포트폴리오에는 참고값으로 표시한다. UNAVAILABLE: bar 자체가
# 없거나(한 번도 수집 안 됨) 환율 등 평가에 필요한 값이 없어 가격을 산출할 수
# 없음 — 0원이나 손실로 계산하지 않고 "확인 불가"로 표시한다.
PRICE_STATUS_FRESH = "FRESH"
PRICE_STATUS_STALE = "STALE"
PRICE_STATUS_UNAVAILABLE = "UNAVAILABLE"
