"""도메인 전반에서 쓰는 상수. 매직 스트링을 한 곳에 모은다."""

ACCOUNT_CASH = "CASH"

ENTRY_INITIAL_DEPOSIT = "INITIAL_DEPOSIT"
ENTRY_BUY_TRADE = "BUY_TRADE"
ENTRY_SELL_TRADE = "SELL_TRADE"

# 주문 상태 머신 (6.6)
ORDER_CREATED = "CREATED"
ORDER_VALIDATED = "VALIDATED"
ORDER_ACCEPTED = "ACCEPTED"
ORDER_PARTIALLY_FILLED = "PARTIALLY_FILLED"
ORDER_FILLED = "FILLED"
ORDER_CANCELLED = "CANCELLED"
ORDER_EXPIRED = "EXPIRED"
ORDER_VALIDATION_FAILED = "VALIDATION_FAILED"
ORDER_REJECTED = "REJECTED"

ORDER_TERMINAL_STATUSES = {
    ORDER_FILLED,
    ORDER_CANCELLED,
    ORDER_EXPIRED,
    ORDER_VALIDATION_FAILED,
    ORDER_REJECTED,
}

EXCHANGE_MARKET_MAP = {
    "KRX": "KR",
    "KOSPI": "KR",
    "KOSDAQ": "KR",
    "NASDAQ": "US",
    "NYSE": "US",
    "AMEX": "US",
}

FEE_POLICY_VERSION = "v1"
